OP_BS_*UTF*: replace VERIFY_IS_MATCH_STATE with asserts
Erlang compiler refuses to compile assembly if src is not a match state.

For example:

```
test_op_bs_get_utf8_asm:1: function bs_get_utf8/1+4:
  Internal consistency check failed - please report this bug.
  Instruction: {test,bs_skip_utf16,
                     {f,3},
                     [{x,0},3,{field_flags,[unsigned,big]}]}
  Error:       {bad_type,{needed,{t_bs_context,1}},{actual,any}}:

```

So we can assume we always have a match state.

Signed-off-by: Paul Guyot <pguyot@kallisys.net>